version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 100
  assignees:
  - andreasots
  groups:
    twilight:
      patterns:
        - twilight-*
    sea-orm:
      patterns:
        - sea-*
    clap:
      patterns:
        - clap
        - clap_*
    lalrpop:
      patterns:
        - lalrpop
        - lalrpop-util
    regex:
      patterns:
        - regex
        - regex-*
        - aho-corasik
    google:
      patterns:
        - google-*
    atrium:
     patterns:
       - atrium-*
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - andreasots
