version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 100
  assignees:
  - andreasots
  groups:
    indirect:
      allow:
        dependency-type: indirect
    twilight:
      patterns:
        - twilight-*
  allow:
  - dependency-type: direct
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - andreasots
